export const data = {
  autopilot: {
    id: 1,
    title: "Autopilot",
    create: "Create your AI extension",
    image: "/assets/images/brain.png",
    cardTitle: "Advanced Negotiation Engine",
    cardText:
      "Never type again - Let AI handle client conversation autometicaly",
    gradient: "Smart Suggestion Engine",
    icon: "assets/icons/star.svg",
    smallTitle: "Predictive property suggestion based on client intent",
    highlight: "Performance",
    bigTitle: "Up to 90%",
    description: "Faster client respones time",
  },
  synergy: {
    id: 2,
    title: "Synergy 75x5",
    create: "Create your AI extension",
    image: "/assets/images/light.png",
    cardTitle: "Real-Time Suggestion Model",
    cardText:
      "Adapts to price, emotion, and context — helping realtors close faster and smarter.",
    gradient: "75 Paths Engine",
    icon: "assets/icons/star.svg",
    smallTitle:
      "Explores 75 negotiation routes, tests outcomes, and picks the one with highest success rate.",
    highlight: "Conversion",
    bigTitle: "Up to 3X",
    description: "Better deal-closing rate",
  },
  ask: {
    id: 3,
    title: "Ask ORACIA",
    create: "Create your AI extension",
    image: "/assets/images/question.png",
    cardTitle: "Remove Any Doubt",
    cardText:
      "Instant answers on listings, prices, or property details — right when you need them.",
    gradient: "Deep Context",
    icon: "assets/icons/star.svg",
    smallTitle:
      "Identifies tone, urgency, and emotion — developing a humanized understanding.",
    highlight: "Privacy First",
    bigTitle: "End-to-End",
    description: "Your workspace, your control",
  },
  crm: {
    id: 4,
    title: "Smart-CRM",
    create: "Create your AI extension",
    image: "/assets/images/smart.png",
    cardTitle: "Smart CRM",
    cardText: "Automatic updating in your sales funnel, lead status and notes",
    gradient: "Automatic Updatest",
    icon: "assets/icons/star.svg",
    smallTitle: "“Conversations — contacts, deals, notes—instantly.“",
    highlight: "Performance",
    bigTitle: "Up to 12 x",
    description: "More agility and precision in data filling",
  },
};